name: Build for Xtreme

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Xtreme Firmware
      uses: actions/checkout@v4
      with:
        repository: Flipper-XFW/Xtreme-Firmware
        submodules: recursive
        path: firmware
        
    - name: Checkout App
      uses: actions/checkout@v4
      with:
        path: app
        
    - name: Copy app
      run: |
        mkdir -p firmware/applications_user/bt_keylogger
        cp app/*.c firmware/applications_user/bt_keylogger/
        cp app/*.h firmware/applications_user/bt_keylogger/
        cp app/application.fam firmware/applications_user/bt_keylogger/
        
    - name: Build
      working-directory: firmware
      run: ./fbt fap_bt_keylogger
        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: bt_keylogger.fap
        path: firmware/build/**/.extapps/*.fap

